# Generated by Django 6.0.6 on 2026-06-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_photo', models.ImageField(blank=True, null=True, upload_to='project_photo/')),
                ('project_Title', models.CharField(max_length=100)),
                ('project_description', models.TextField(max_length=2000)),
                ('project_tag', models.CharField(max_length=40)),
                ('project_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
