# Generated by Django 6.0.6 on 2026-06-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_homeproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolioproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_image', models.ImageField(blank=True, null=True, upload_to='portfolio_photo/')),
                ('portfolio_Title', models.CharField(max_length=100)),
                ('portfolio_description', models.TextField(max_length=2000)),
                ('portfolio_tag', models.CharField(max_length=40)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
