# Generated by Django 6.0.4 on 2026-06-15 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_portfolioproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeproject',
            name='project_photo',
        ),
        migrations.CreateModel(
            name='homeprojectimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_photo/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.homeproject')),
            ],
        ),
    ]
