# Generated by Django 6.0.4 on 2026-06-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_homeproject_project_photo_homeprojectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='project_photo',
            field=models.ImageField(blank=True, null=True, upload_to='project_photo/'),
        ),
        migrations.DeleteModel(
            name='homeprojectimage',
        ),
    ]
