# Generated by Django 6.0.6 on 2026-06-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_homeproject_project_photo_delete_homeprojectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_testimonial', models.TextField(max_length=2000)),
                ('client_company', models.CharField(max_length=100)),
            ],
        ),
    ]